### PR TITLE
Use python-casacore's pending MeasurementSet creation functionality for creating Fixed Shape columns

### PR DESCRIPTION
**Pull request by sjperkins**
Previously, h5toms created variable length data columns when creating a MeasurementSet. Catering for this variability means the MS's are not performant. This PR 

1. Modifies h5toms to use python-casacore's upcoming functionality for creating canonical Measurement Set's. This removes the need to maintain table definitions for the MS within katdal.
2. Modfies h5toms to define fixed shape columns for `DATA`, `MODEL_DATA`, `CORRECTED_DATA`, `FLAG`, `FLAG_CATEGORY`, `IMAGING_WEIGHTS`, `WEIGHTS` and `SIGMA`, as well as the original hypercolumn definitions that were bases on these columns.

Depends on https://github.com/casacore/python-casacore/pull/72.

### CODE REVIEW

**Comment by sjperkins** [comment]
@ludwigschwardt Still a WIP, I'll request a review when ready.

**Comment by sjperkins** [comment]
Some indicators of performance on my laptop. From a brief look I don't think writing to the MS is the bottleneck, since my OS disk indicator shows 90 - 100 MB/s during these extended write periods. I would guess its the h5 reads.

```bash
Writing static meta data...
scan   1 ( 151 samples) loaded. Target: '3C138'. Writing to disk...
Wrote scan data (1091.067221 MB) in 42.674429 s (25.567237 MBps)

scan   3 (  31 samples) loaded. Target: 'PKS 1607-841'. Writing to disk...
Wrote scan data (223.993933 MB) in 18.888033 s (11.859040 MBps)

scan   5 ( 151 samples) loaded. Target: 'SCP'. Writing to disk...
Wrote scan data (1091.067221 MB) in 50.204534 s (21.732444 MBps)
```

When writing model and corrected data the situation "improves":

```bash
Writing static meta data...
scan   1 ( 151 samples) loaded. Target: '3C138'. Writing to disk...
Wrote scan data (2336.817221 MB) in 43.564234 s (53.640728 MBps)

scan   3 (  31 samples) loaded. Target: 'PKS 1607-841'. Writing to disk...
Wrote scan data (479.743933 MB) in 19.703434 s (24.348240 MBps)

scan   5 ( 151 samples) loaded. Target: 'SCP'. Writing to disk...
Wrote scan data (2336.817221 MB) in 48.277194 s (48.404164 MBps)

scan   7 (  73 samples) loaded. Target: 'PKS 1607-841'. Writing to disk...
Wrote scan data (1129.719584 MB) in 23.365508 s (48.349883 MBps)
```

**Comment by bennahugo** [comment]
These changes work quite well in our pipeline. I've been running them since Stimela 0.2.8 on a regular basis. As soon as the PRs go into python-casacore I'd recommend that we integrate.

**Comment by ludwigschwardt** [comment]
Is this PR ready to use now?

**Comment by sjperkins** [comment]
> Is this PR ready to use now?

Provisionally. However, In order to use this PR:

1. A manual build of casascore 2.3.0 is required (but not difficult).
2. pip install of python-casacore master branch (unpleasant).

Unfortunately, none of the functionality in points (1) and (2) is available in a kernsuite release (yet).

**Comment by sjperkins** [comment]
With the:

- inclusion of casacore 2.3.0 in [kern-2](https://launchpad.net/~kernsuite/+archive/ubuntu/kern-2)
- inclusion of casacore 2.4.0 in [kern-3](https://launchpad.net/~kernsuite/+archive/ubuntu/kern-3)
- release of python-casacore 2.2.0 in [kern-3](https://launchpad.net/~kernsuite/+archive/ubuntu/kern-3) and [pypi](https://pypi.python.org/pypi/python-casacore/2.2.0)

I think this feature is ready to be merged.

/cc @bennahugo @sphemakh @gijzelaerr @ludwigschwardt

**Comment by sjperkins** [comment]
Could a RATT go test this works with kern-3 casacore 2.4.0 and python-casacore 2.2.0. Modify https://github.com/SpheMakh/Stimela/blob/master/stimela/cargo/base/katdal/Dockerfile to

1. remove custom casacore 2.3.0 build
2. Add kern-3 repo
3. docker-apt-install casacore==2.4.0
4. pip install python-casacore==2.2.0
5. Retain pip install of custom katdal branch (tracking this PR).

If that works, I reckon @gijzelaerr could press the big green merge button with @ludwigschwardt noticing ;-)

**Comment by SpheMakh** [comment]
It works when using kern-3 python-casacore, But the PyPI version of python-casacore is [broken](https://github.com/casacore/python-casacore/issues/124)

**Comment by sjperkins** [comment]
Can this be merged now that python-casacore 2.2.1 is released?

**Comment by ludwigschwardt** [comment]
For the record, I bumped the casacore brew formula to 2.4.0, so the new combination should work on the Mac too (time to test...).

**Pull request merged**
